nxp/backoffice/rewards/urls.py
from django.urls import path, include
from .views import *

app_name = "rewards"
urlpatterns = [
    path("transactions/", transactions, name="transactions"),
    path("", redeem, name="redeem"),
    path('<int:id>/redeem-detail/', redeem_detail, name='redeem_detail'),
    path('<int:id>/set-as-paid/', set_as_paid, name='set_as_paid'),
]

nxp/backoffice/urls.py
from django.urls import path, include
from .views import (
    login_view, log_out, index, 
    generate_json_data,
    process_data,
    json_data, 
    json_data_detail,

    purchase_invoice_item,
    purchase_invoice_expense,
    cashflow, 
    jv,
    invoice,
    download_file
)

app_name = "backoffice"
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('log_out/', log_out, name='log_out'),

    path('purchase-invoice-item/', purchase_invoice_item, name='purchase_invoice_item'),
    path('purchase-invoice-expense/', purchase_invoice_expense, name='purchase_invoice_expense'),
    path('cashflow/', cashflow, name='cashflow'),
    path('jv/', jv, name='jv'),
    path('invoice/', invoice, name='invoice'),

    path('generate-json-data/', generate_json_data, name='generate_json_data'),
    path('json-data/', json_data, name='json_data'),
    path('<int:id>/json-data-detail/', json_data_detail, name='json_data_detail'),
    path('process-data/', process_data, name='process_data'),
    path('download/<str:filename>', download_file, name="download_file"),
]

nxp/backoffice/users/urls.py
from django.urls import path, include
from .views import *

app_name = "users"
urlpatterns = [
    path("", users, name="users"),
    path('<int:id>/user-detail/', user_detail, name='user_detail'),
]

nxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import auth

admin.site.site_header = "Import Excell Admin"
admin.site.site_title = "Import Excell Admin "
admin.site.index_title = "Welcome to Import Excell Admin "

# admin.site.unregister(auth.models.Group)


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('nxp.backoffice.urls', namespace='backoffice')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

nxp/apps/cashflow/models.py
from django.db import models
from django.utils import timezone
from .models import *
from datetime import datetime, timedelta


class Cashflow(models.Model):
    class Meta:
        verbose_name_plural = "Cashflow"
    id = models.AutoField(primary_key=True)
    tgl_jv = models.CharField(max_length=100, blank=True, null=True) #a
    no_akun = models.CharField(max_length=100, blank=True, null=True) #b
    nama_akun = models.CharField(max_length=100, blank=True, null=True) #c
    catatan = models.CharField(max_length=100, blank=True, null=True) #d
    nilai_asing = models.CharField(max_length=100, blank=True, null=True) #e
    nama_dep = models.CharField(max_length=100, blank=True, null=True) #f
    nama_proyek = models.CharField(max_length=100, blank=True, null=True) #g
    no_jv = models.CharField(max_length=100, blank=True, null=True) #h
    bank_code = models.CharField(max_length=100, blank=True, null=True) #i
    nama_bank = models.CharField(max_length=100, blank=True, null=True) #j
    type = models.CharField(max_length=100, blank=True, null=True) #k

    def __str__(self):
        return f"{self.no_jv}"

    def generate_json_all_data(self):
        data_to_summarize = {}
        for dt in Cashflow.objects.all():
            # nilai_assing = dt.nilai_asing.replace(".", "").replace(",","")
            nilai_assing = dt.nilai_asing
            dt_detil = {
                "accountCode": dt.no_akun or "", #b
                "amount": int(nilai_assing) or "", #e
                "description": dt.nama_akun or "", #c
                "deptCode": dt.nama_dep or "", #f
                "prjCode": "" #null
            }
            if data_to_summarize.get(dt.no_jv) is None:
                data_to_summarize[dt.no_jv] = {
                    "no": dt.no_jv or "", #H
                    "dt": f"{dt.tgl_jv} 00:00:00", #A
                    "type": dt.type or "", #st
                    "locCode": "HO", #st
                    "bankCode": dt.bank_code or "", #i
                    "createBy": "admin", #st
                    "confirmBy": "admin", #st
                    "remark": dt.catatan or "", #d
                    "referenceNo": "0", #static
                    "bankIssuer": "0", #static
                    "amount": int(nilai_assing) or "", #sum(e)
                    "details": [dt_detil] or "",                    
                    "item_joined": 1, #helper
                }
            else: 
                data_to_summarize[dt.no_jv]["item_joined"] += 1
                data_to_summarize[dt.no_jv]["amount"] += int(nilai_assing)
                data_to_summarize[dt.no_jv]["details"].append(dt_detil)

        return data_to_summarize

# def save_to_json_data():
#     datas = generate_json_all_data()
    # Save to db
  
# test
# from nxp.apps.cashflow.models import *
# generate_json_all_data

nxp/apps/lastkey/models.py
from django.db import models

class LastKey(models.Model):
    id = models.AutoField(primary_key=True)
    last_key = models.CharField(max_length=100)
   
    def __str__(self):
        return f"{self.last_key}"

nxp/backoffice/forms.py
from django import forms
from django.contrib import auth


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()


class UploadExcellForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

nxp/backoffice/users/forms.py
# from SahabatElvineDjango.apps.news.models import News
# from django import forms


# class AddNewsForm(forms.ModelForm):
#     name = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control'}), required=False)
#     description = forms.CharField(
#         widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
#     short_description = forms.CharField(
#         widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
#     picture1 = forms.ImageField(
#         required=True, help_text="Ukuran gambar harus 500PX * 270PX")
#     picture2 = forms.ImageField(required=False)
#     picture3 = forms.ImageField(required=False)
#     date = forms.ImageField(required=False)

#     class Meta:
#         model = News
#         fields = '__all__'

#     def clean_picture1(self):
#         picture1 = self.cleaned_data.get('picture1', False)
#         if picture1:
#             if picture1.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture1 file too large ( > 0.5mb )")
#         return picture1

#     def clean_picture2(self):
#         picture2 = self.cleaned_data.get('picture2', False)
#         if picture2:
#             if picture2.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture2 file too large ( > 0.5mb )")
#         return picture2

#     def clean_picture3(self):
#         picture3 = self.cleaned_data.get('picture3', False)
#         if picture3:
#             if picture3.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture3 file too large ( > 0.5mb )")
#         return picture3

nxp/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

nxp/backoffice/formulir/views.py
# -*- coding: utf-8 -*-
# from django.contrib import messages
# from .forms import AddNewsForm
# from django.urls import reverse
# from django.shortcuts import redirect, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse

from nxp.apps.formulir.models import Formulir
from nxp.apps.user.decorators import login_validate


@login_validate
def index(request):
    formulirs = Formulir.objects.all().order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        formulirs = formulirs.filter(Q(name=search) | Q(mobile_number=search))
    ewallet = request.GET.get("ewallet")
    if ewallet:
        formulirs = formulirs.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        formulirs = formulirs.filter(status=status)

    results_per_page = 30
    new_count = formulirs.filter(status="new").count()
    paid_count = formulirs.filter(status="paid").count()
    cancel_count = formulirs.filter(status="paid").count()

    paginator = Paginator(formulirs, results_per_page)
    try:
        formulirs = paginator.get_page(page)
    except PageNotAnInteger:
        formulirs = paginator.get_page(1)
    except EmptyPage:
        formulirs = paginator.get_page(paginator.num_pages)

    context = {
        "formulirs": formulirs,
        "title": "Fromulir",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/formulir/index.html", context)


# @login_validate
# def add(request):
#     form = AddNewsForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         form.save()
#         messages.success(request, 'success')
#         return redirect(reverse('backoffice:news:index'))

#     context = dict(
#         form=form,
#         title='Add New'
#     )
#     return TemplateResponse(request, 'backoffice/news/add.html', context)


# @login_validate
# def edit(request, id):
#     news = get_object_or_404(News, id=id)
#     form = AddNewsForm(
#       request.POST or None, request.FILES or None, instance=news)
#     if form.is_valid():
#         form.save()
#         return redirect(reverse('backoffice:news:index'))

#     context = dict(
#         form=form,
#         title='Edit User'
#     )
#     return TemplateResponse(request, 'backoffice/news/add.html', context)


# @login_validate
# def delete(request, id):
#     news = get_object_or_404(News, id=id)
#     news.delete()
#     return redirect('backoffice:news:index')

nxp/backoffice/rewards/views.py
import csv
import datetime
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.reward.models import Redeem, Scan
from nxp.apps.user.decorators import login_validate
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponse


@login_validate
def redeem(request):
    redeems = Redeem.objects.select_related('user').order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        redeems = redeems.filter(Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search))

    ewallet = request.GET.get("ewallet")
    if ewallet:
        redeems = redeems.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        redeems = redeems.filter(status=status)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="redeem.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name', 'Nominal', 'E-Wallet', 'Status'])
        idx = 0
        for sr in redeems:
            idx += 1
            writer.writerow([idx, sr.user.name, sr.dealer_code, sr.user.mobile_number,
                             sr.value, sr.get_wallet_type_display(), sr.status])
        return response

    results_per_page = 30
    new_count = redeems.filter(status="new").count()
    paid_count = redeems.filter(status="paid").count()
    cancel_count = redeems.filter(status="paid").count()

    paginator = Paginator(redeems, results_per_page)
    try:
        redeems = paginator.get_page(page)
    except PageNotAnInteger:
        redeems = paginator.get_page(1)
    except EmptyPage:
        redeems = paginator.get_page(paginator.num_pages)

    context = {
        "redeems": redeems,
        "title": "Redeem",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/rewards/index.html", context)


@login_validate
def transactions(request):
    scans = Scan.objects.all().order_by("-id").select_related('user')\
        .select_related('serial_number').order_by('-datetime')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    if search:
        scans = scans.filter(
            Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search) | Q(serial_number__serial_number__icontains=search))

    if start and end:
        scans = scans.filter(datetime__range=[start, end])

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Serial', 'Name', 'Date', 'Value'])
        idx = 0
        
        for sr in scans:
            idx += 1
            _datetime = sr.datetime.strftime("%m/%d/%Y, %H:%M")
            _datetime = datetime.datetime.strptime(_datetime, "%m/%d/%Y, %H:%M")
            writer.writerow([idx, sr.serial_number, sr.user.name, _datetime,
                             sr.serial_number.value])
        return response

    results_per_page = 30
    paginator = Paginator(scans, results_per_page)
    try:
        scans = paginator.get_page(page)
    except PageNotAnInteger:
        scans = paginator.get_page(1)
    except EmptyPage:
        scans = paginator.get_page(paginator.num_pages)

    context = {
        "scans": scans,
        "title": "Transactions",
        "filter": {"search": search, "start": start, "end": end},
    }
    return TemplateResponse(request, "backoffice/rewards/transactions.html", context)

@login_validate
def redeem_detail(request, id):
    redeem = Redeem.objects.get(id=id)
    context = {
        "redeem": redeem,
        'vrer':  request.session
    }
    return TemplateResponse(request, "backoffice/rewards/redeem-detail.html", context)


@login_validate
def set_as_paid(request, id):
    redeem = get_object_or_404(Redeem, id=id)
    if redeem.status == 'paid':
        return JsonResponse({"message": "redeem already paid"}, status = 400)
    else:
        redeem.status = 'paid'
        redeem.paid_datetime = timezone.now()
        redeem.admin = request.user
        redeem.save()
        return JsonResponse({"message": "redeem already paid"}, status = 200)

    

nxp/backoffice/users/views.py
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.user.models import User
from nxp.apps.reward.models import Scan
from nxp.apps.user.decorators import login_validate
from django.http import HttpResponse


@login_validate
def users(request):
    users = User.objects.all().order_by("-id").exclude(is_superuser=True)
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        users = users.filter(
            Q(name__icontains=search) | Q(mobile_number__icontains=search) |
            Q(dealer_name__icontains=search)
        )

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="users.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name'])
        idx = 0
        for sr in users:
            idx += 1
            writer.writerow([idx, sr.name, sr.mobile_number, sr.dealer_name])
        return response

    results_per_page = 30
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "User",
        "filter": {"search": search},
    }
    return TemplateResponse(request, "backoffice/users/index.html", context)

@login_validate
def user_detail(request, id):
    user = User.objects.get(id=id)
    scans = Scan.objects.filter(user=user).order_by('-datetime').select_related('serial_number')
    context = {
        "user": user,
        "title": "User Detail",
        "scans": scans[0:8]
    }
    return TemplateResponse(request, "backoffice/users/user-detail.html", context)

nxp/templates/backoffice/invoice/cashflow-detail.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
{% load humanize %}
<div class="box margin-top-profile">
    <h2 class="profile__name">{{ user.name|upper }}</h2>
    <h4>{{ user.mobile_number }} - {{ user.dealer_name }}</h4>
    <h4>Address: {{ user.dealer_address }}</h4>
    <hr />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Serial</th>
          <th>Date</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        {% for scan in scans %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ scan.serial_number }}</td>
          <td>{{ scan.datetime }}</td>
          <td>{{ scan.serial_number.value|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <hr />
    <a class="btn btn-primary"
      href="{% url 'backoffice:rewards:transactions' %}?search={{ user.username|slice:'1:' }}">More Data</a>
</div>
{% endblock %}

nxp/templates/backoffice/invoice/index.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% load humanize %}
{% load templatehelpers %}
{% block title%} {{ title }} {% endblock %}
{% block content %}
<div class="box">
    <div class="box-inner">
      <div class="box-title">
        <h2>{{title}}</h2>
      </div>

      <div class="box-title">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-sm-4">
              <div class="input-group">
                <input type="file" name="myfile" 
                required
                placeholder="File CSV" >
              </div>
            </div>
            <div class="col-sm-4">
              <a class="btn btn-primary" href="{% url 'backoffice:download_file' filename='Invoice.csv' %}">Download Sample CSV</a>
              <button type="submit" id="btn-search-fix-h" class="btn btn-primary">
                Import CSV
              </button>
            </div>
              <div class="col-sm-2">
              <button id="GenerateButton" type="button"  class="btn btn-primary">
                Generate JSON DATA
              </button>
            </div>
          </div>
        </form>
      </div>

      

      {% comment %} <div class="box-title">
        <form method="GET" action="">
          <div class="row">
            <div class="col-sm-4">
              <div class="input-group">
                <input type="text" name="search" class="form-control" 
                  placeholder="No Akun / Nama Akun / NO JV" value="{{ filter.search }}">
              </div>
            </div>
            <div class="col-sm-2">
              <button type="submit" id="btn-search-fix-h" class="btn btn-primary">
                CARI DATA
              </button>
            </div>
          </div>
        </form>
      </div>  {% endcomment %}
      
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nomor Faktur</th>
            <th>Nama Pelanggan</th>
          </tr>
        </thead>
        <tbody>
        {% for data in datas %}
          <tr>
            <td>{{ data.no_faktur }}</td>
            <td>{{ data.nama_pelanggan }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
  
      <div class="pull-right">
        <p>Page {{ datas.number }} of {{ datas.paginator.num_pages }}</p>
        <nav aria-label="">
          <ul class="pagination">
            {% if datas.has_previous %}
            <li class="page-item"><a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
            </li>
            <li class="page-item"><a class="page-link"
                href="{% relative_url datas.previous_page_number 'page' request.GET.urlencode %}">Previous</a></li>
            {% endif %}
            {% if datas.has_next %}
            <li class="page-item"><a class="page-link"
                href="{% relative_url datas.next_page_number 'page' request.GET.urlencode %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>

  </div>
{% endblock %}

{% block script %} 
<script type="text/javascript"> 
$("#GenerateButton").on('click', function () {
  $.ajax({
    type: 'GET',
    url: "{% url 'backoffice:generate_json_data' %}?app=invoice&model=Invoice&type=invoice",
    success: function (response) {
      alert("Success")
    },
    error: function (response) {
      alert("error")
    }
  });
})
</script>
{% endblock %}