nxp/backoffice/rewards/urls.py
from django.urls import path, include
from .views import *

app_name = "rewards"
urlpatterns = [
    path("transactions/", transactions, name="transactions"),
    path("", redeem, name="redeem"),
    path('<int:id>/redeem-detail/', redeem_detail, name='redeem_detail'),
    path('<int:id>/set-as-paid/', set_as_paid, name='set_as_paid'),
]

nxp/backoffice/urls.py
from django.urls import path, include
from .views import (
    login_view, log_out, index, 
    generate_json_data,
    process_data,
    json_data, 
    json_data_detail,

    purchase_invoice_item,
    purchase_invoice_expense,
    cashflow, 
    jv,
    invoice,
    download_file
)

app_name = "backoffice"
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('log_out/', log_out, name='log_out'),

    path('purchase-invoice-item/', purchase_invoice_item, name='purchase_invoice_item'),
    path('purchase-invoice-expense/', purchase_invoice_expense, name='purchase_invoice_expense'),
    path('cashflow/', cashflow, name='cashflow'),
    path('jv/', jv, name='jv'),
    path('invoice/', invoice, name='invoice'),

    path('generate-json-data/', generate_json_data, name='generate_json_data'),
    path('json-data/', json_data, name='json_data'),
    path('<int:id>/json-data-detail/', json_data_detail, name='json_data_detail'),
    path('process-data/', process_data, name='process_data'),
    path('download/<str:filename>', download_file, name="download_file"),
]

nxp/backoffice/users/urls.py
from django.urls import path, include
from .views import *

app_name = "users"
urlpatterns = [
    path("", users, name="users"),
    path('<int:id>/user-detail/', user_detail, name='user_detail'),
]

nxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import auth

admin.site.site_header = "Import Excell Admin"
admin.site.site_title = "Import Excell Admin "
admin.site.index_title = "Welcome to Import Excell Admin "

# admin.site.unregister(auth.models.Group)


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('nxp.backoffice.urls', namespace='backoffice')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

nxp/apps/cashflow/models.py
from django.db import models
from django.utils import timezone
from .models import *
from datetime import datetime, timedelta


class Cashflow(models.Model):
    class Meta:
        verbose_name_plural = "Cashflow"
    id = models.AutoField(primary_key=True)
    tgl_jv = models.CharField(max_length=100, blank=True, null=True) #a
    no_akun = models.CharField(max_length=100, blank=True, null=True) #b
    nama_akun = models.CharField(max_length=100, blank=True, null=True) #c
    catatan = models.CharField(max_length=100, blank=True, null=True) #d
    nilai_asing = models.CharField(max_length=100, blank=True, null=True) #e
    nama_dep = models.CharField(max_length=100, blank=True, null=True) #f
    nama_proyek = models.CharField(max_length=100, blank=True, null=True) #g
    no_jv = models.CharField(max_length=100, blank=True, null=True) #h
    bank_code = models.CharField(max_length=100, blank=True, null=True) #i
    nama_bank = models.CharField(max_length=100, blank=True, null=True) #j
    type = models.CharField(max_length=100, blank=True, null=True) #k

    def __str__(self):
        return f"{self.no_jv}"

    def generate_json_all_data(self):
        data_to_summarize = {}
        for dt in Cashflow.objects.all():
            # nilai_assing = dt.nilai_asing.replace(".", "").replace(",","")
            nilai_assing = dt.nilai_asing
            dt_detil = {
                "accountCode": dt.no_akun or "", #b
                "amount": int(nilai_assing) or "", #e
                "description": dt.nama_akun or "", #c
                "deptCode": dt.nama_dep or "", #f
                "prjCode": "" #null
            }
            if data_to_summarize.get(dt.no_jv) is None:
                data_to_summarize[dt.no_jv] = {
                    "no": dt.no_jv or "", #H
                    "dt": f"{dt.tgl_jv} 00:00:00", #A
                    "type": dt.type or "", #st
                    "locCode": "HO", #st
                    "bankCode": dt.bank_code or "", #i
                    "createBy": "admin", #st
                    "confirmBy": "admin", #st
                    "remark": dt.catatan or "", #d
                    "referenceNo": "0", #static
                    "bankIssuer": "0", #static
                    "amount": int(nilai_assing) or "", #sum(e)
                    "details": [dt_detil] or "",                    
                    "item_joined": 1, #helper
                }
            else: 
                data_to_summarize[dt.no_jv]["item_joined"] += 1
                data_to_summarize[dt.no_jv]["amount"] += int(nilai_assing)
                data_to_summarize[dt.no_jv]["details"].append(dt_detil)

        return data_to_summarize

# def save_to_json_data():
#     datas = generate_json_all_data()
    # Save to db
  
# test
# from nxp.apps.cashflow.models import *
# generate_json_all_data

nxp/apps/lastkey/models.py
from django.db import models

class LastKey(models.Model):
    id = models.AutoField(primary_key=True)
    last_key = models.CharField(max_length=100)
   
    def __str__(self):
        return f"{self.last_key}"

nxp/backoffice/forms.py
from django import forms
from django.contrib import auth


class LoginForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()


class UploadExcellForm(auth.forms.AuthenticationForm):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

    def clean(self):
        return super(LoginForm, self).clean()

nxp/backoffice/users/forms.py
# from SahabatElvineDjango.apps.news.models import News
# from django import forms


# class AddNewsForm(forms.ModelForm):
#     name = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control'}), required=False)
#     description = forms.CharField(
#         widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)
#     short_description = forms.CharField(
#         widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
#     picture1 = forms.ImageField(
#         required=True, help_text="Ukuran gambar harus 500PX * 270PX")
#     picture2 = forms.ImageField(required=False)
#     picture3 = forms.ImageField(required=False)
#     date = forms.ImageField(required=False)

#     class Meta:
#         model = News
#         fields = '__all__'

#     def clean_picture1(self):
#         picture1 = self.cleaned_data.get('picture1', False)
#         if picture1:
#             if picture1.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture1 file too large ( > 0.5mb )")
#         return picture1

#     def clean_picture2(self):
#         picture2 = self.cleaned_data.get('picture2', False)
#         if picture2:
#             if picture2.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture2 file too large ( > 0.5mb )")
#         return picture2

#     def clean_picture3(self):
#         picture3 = self.cleaned_data.get('picture3', False)
#         if picture3:
#             if picture3.size > 0.5 * 1024 * 1024:
#                 raise forms.ValidationError(
#                     "picture3 file too large ( > 0.5mb )")
#         return picture3

nxp/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

nxp/backoffice/formulir/views.py
# -*- coding: utf-8 -*-
# from django.contrib import messages
# from .forms import AddNewsForm
# from django.urls import reverse
# from django.shortcuts import redirect, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse

from nxp.apps.formulir.models import Formulir
from nxp.apps.user.decorators import login_validate


@login_validate
def index(request):
    formulirs = Formulir.objects.all().order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        formulirs = formulirs.filter(Q(name=search) | Q(mobile_number=search))
    ewallet = request.GET.get("ewallet")
    if ewallet:
        formulirs = formulirs.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        formulirs = formulirs.filter(status=status)

    results_per_page = 30
    new_count = formulirs.filter(status="new").count()
    paid_count = formulirs.filter(status="paid").count()
    cancel_count = formulirs.filter(status="paid").count()

    paginator = Paginator(formulirs, results_per_page)
    try:
        formulirs = paginator.get_page(page)
    except PageNotAnInteger:
        formulirs = paginator.get_page(1)
    except EmptyPage:
        formulirs = paginator.get_page(paginator.num_pages)

    context = {
        "formulirs": formulirs,
        "title": "Fromulir",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/formulir/index.html", context)


# @login_validate
# def add(request):
#     form = AddNewsForm(request.POST or None, request.FILES or None)
#     if form.is_valid():
#         form.save()
#         messages.success(request, 'success')
#         return redirect(reverse('backoffice:news:index'))

#     context = dict(
#         form=form,
#         title='Add New'
#     )
#     return TemplateResponse(request, 'backoffice/news/add.html', context)


# @login_validate
# def edit(request, id):
#     news = get_object_or_404(News, id=id)
#     form = AddNewsForm(
#       request.POST or None, request.FILES or None, instance=news)
#     if form.is_valid():
#         form.save()
#         return redirect(reverse('backoffice:news:index'))

#     context = dict(
#         form=form,
#         title='Edit User'
#     )
#     return TemplateResponse(request, 'backoffice/news/add.html', context)


# @login_validate
# def delete(request, id):
#     news = get_object_or_404(News, id=id)
#     news.delete()
#     return redirect('backoffice:news:index')

nxp/backoffice/rewards/views.py
import csv
import datetime
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.reward.models import Redeem, Scan
from nxp.apps.user.decorators import login_validate
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.http import HttpResponse


@login_validate
def redeem(request):
    redeems = Redeem.objects.select_related('user').order_by("-id")
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        redeems = redeems.filter(Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search))

    ewallet = request.GET.get("ewallet")
    if ewallet:
        redeems = redeems.filter(wallet_type=ewallet)
    status = request.GET.get("status")
    if status:
        redeems = redeems.filter(status=status)

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="redeem.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name', 'Nominal', 'E-Wallet', 'Status'])
        idx = 0
        for sr in redeems:
            idx += 1
            writer.writerow([idx, sr.user.name, sr.dealer_code, sr.user.mobile_number,
                             sr.value, sr.get_wallet_type_display(), sr.status])
        return response

    results_per_page = 30
    new_count = redeems.filter(status="new").count()
    paid_count = redeems.filter(status="paid").count()
    cancel_count = redeems.filter(status="paid").count()

    paginator = Paginator(redeems, results_per_page)
    try:
        redeems = paginator.get_page(page)
    except PageNotAnInteger:
        redeems = paginator.get_page(1)
    except EmptyPage:
        redeems = paginator.get_page(paginator.num_pages)

    context = {
        "redeems": redeems,
        "title": "Redeem",
        "filter": {"search": search, "status": status, "ewallet": ewallet},
        "new_count": new_count,
        "paid_count": paid_count,
        "cancel_count": cancel_count,
    }
    return TemplateResponse(request, "backoffice/rewards/index.html", context)


@login_validate
def transactions(request):
    scans = Scan.objects.all().order_by("-id").select_related('user')\
        .select_related('serial_number').order_by('-datetime')
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    if search:
        scans = scans.filter(
            Q(user__name__icontains=search) | Q(user__mobile_number__icontains=search) | Q(serial_number__serial_number__icontains=search))

    if start and end:
        scans = scans.filter(datetime__range=[start, end])

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Serial', 'Name', 'Date', 'Value'])
        idx = 0
        
        for sr in scans:
            idx += 1
            _datetime = sr.datetime.strftime("%m/%d/%Y, %H:%M")
            _datetime = datetime.datetime.strptime(_datetime, "%m/%d/%Y, %H:%M")
            writer.writerow([idx, sr.serial_number, sr.user.name, _datetime,
                             sr.serial_number.value])
        return response

    results_per_page = 30
    paginator = Paginator(scans, results_per_page)
    try:
        scans = paginator.get_page(page)
    except PageNotAnInteger:
        scans = paginator.get_page(1)
    except EmptyPage:
        scans = paginator.get_page(paginator.num_pages)

    context = {
        "scans": scans,
        "title": "Transactions",
        "filter": {"search": search, "start": start, "end": end},
    }
    return TemplateResponse(request, "backoffice/rewards/transactions.html", context)

@login_validate
def redeem_detail(request, id):
    redeem = Redeem.objects.get(id=id)
    context = {
        "redeem": redeem,
        'vrer':  request.session
    }
    return TemplateResponse(request, "backoffice/rewards/redeem-detail.html", context)


@login_validate
def set_as_paid(request, id):
    redeem = get_object_or_404(Redeem, id=id)
    if redeem.status == 'paid':
        return JsonResponse({"message": "redeem already paid"}, status = 400)
    else:
        redeem.status = 'paid'
        redeem.paid_datetime = timezone.now()
        redeem.admin = request.user
        redeem.save()
        return JsonResponse({"message": "redeem already paid"}, status = 200)

    

nxp/backoffice/users/views.py
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.template.response import TemplateResponse
from nxp.apps.user.models import User
from nxp.apps.reward.models import Scan
from nxp.apps.user.decorators import login_validate
from django.http import HttpResponse


@login_validate
def users(request):
    users = User.objects.all().order_by("-id").exclude(is_superuser=True)
    page = request.GET.get("page")
    search = request.GET.get("search", "")
    if search:
        users = users.filter(
            Q(name__icontains=search) | Q(mobile_number__icontains=search) |
            Q(dealer_name__icontains=search)
        )

    action = request.GET.get("action")
    if action == 'export':
        response = HttpResponse(
            content_type='text/csv',
        )
        response['Content-Disposition'] = 'attachment; filename="users.csv"'
        writer = csv.writer(response)
        writer.writerow(['No', 'Name', 'Mobile Number', 'Dealer Name'])
        idx = 0
        for sr in users:
            idx += 1
            writer.writerow([idx, sr.name, sr.mobile_number, sr.dealer_name])
        return response

    results_per_page = 30
    paginator = Paginator(users, results_per_page)
    try:
        users = paginator.get_page(page)
    except PageNotAnInteger:
        users = paginator.get_page(1)
    except EmptyPage:
        users = paginator.get_page(paginator.num_pages)

    context = {
        "users": users,
        "title": "User",
        "filter": {"search": search},
    }
    return TemplateResponse(request, "backoffice/users/index.html", context)

@login_validate
def user_detail(request, id):
    user = User.objects.get(id=id)
    scans = Scan.objects.filter(user=user).order_by('-datetime').select_related('serial_number')
    context = {
        "user": user,
        "title": "User Detail",
        "scans": scans[0:8]
    }
    return TemplateResponse(request, "backoffice/users/user-detail.html", context)

nxp/templates/backoffice/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% block extra_header %} {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{% static 'css/trackpad-scroll-emulator.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery.raty.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/explorer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sweetalert2.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/loading.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="/static/autocomplete_light/select2.css" rel="stylesheet" type="text/css"> -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/ico/sahabatelvine.ico'%}"> -->
  </head>
  <body class="">
    <div class="admin-wrapper">
      <div class="admin-sidebar">
        <div class="admin-sidebar-header">
          <div class="admin-sidebar-logo">
            <a href="/">
              <!-- <img src="{% static 'img/logo/logo.png' %}" class="svg" alt="Home"> -->
            </a>
            <a href="/" class="admin-sidebar-logo-title">
              <strong>DATA MIGRATION</strong>
              <span>---------------------------------------</span>
            </a>
          </div>
          <!-- /.admin-sidebar-logo -->
        </div>
        <!-- /.admin-sidebar-header -->
        <div class="admin-sidebar-content">
          <h3>Menu</h3>
          <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'backoffice:index' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:index' %} active {% endif %}">
                  <i class="fa fa-tachometer"></i><span>Dashboard</span>
                </a>
            </li>
          </ul>


          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:purchase_invoice_item' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Purchase Invoice</span>
              </a>
            </li>
          </ul>

          {% comment %} <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:purchase_invoice_expense' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Purchase Inv Expense</span>
              </a>
            </li>
          </ul> {% endcomment %}


          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:cashflow' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Cashflow</span>
              </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:jv' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>JV</span>
              </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:invoice' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Invoice</span>
              </a>
            </li>
          </ul>

          <ul class="nav flex-column">
            <li class="nav-item">
              <a href="{% url 'backoffice:json_data' %}" class="nav-link {% if request.resolver_match.view_name == 'backoffice:rewards:transactions' %} active {% endif %}">
                <i class="fa fa-check-square"></i><span>Json Data</span>
              </a>
            </li>
          </ul>

        </div>
        <!-- /.admin-sidebar-content -->
        <div class="admin-sidebar-footer">
          <strong></strong>
          <span>&copy; </span>
        </div>
        <!-- /.admin-sidebar-footer -->
      </div>
      <!-- /.admin-sidebar -->
      <div class="admin-main">
        <div class="admin-header">
          <div class="container-fluid">
            
            <div class="admin-header-avatar">
              <!-- <span class="avatar" style="background-image: {% static 'images/user.png' %}"></span> -->
              <span class="admin-header-avatar-name">{{ request.user.username|title }}<i class="fa fa-chevron-down"></i></span>
              <ul class="admin-header-avatar-menu">
                <li><a href="#">{{ request.user.username|title }}</a></li>
                <li><a href="{% url 'backoffice:log_out' %}">Sign Out</a></li>
              </ul>
              <!-- /.admin-header-avatar-menu -->
            </div>
            <!-- /.admin-header-actions -->
          </div>
          <!-- /.container -->
        </div>
        <!-- /.admin-header -->
        <div class="admin-content">
          <div class="container-fluid">
            {% block breadcrumb %}
            <nav class="breadcrumb">
              <a class="breadcrumb-item" href="#">Home</a>
              <a class="breadcrumb-item" href="#">Library</a>
              <a class="breadcrumb-item" href="#">Data</a>
              <span class="breadcrumb-item active">Bootstrap</span>
            </nav>
            {% endblock %}

            {% block content %} {% endblock %}
            <!-- /.box -->
          </div>
          <!-- /.container -->
        </div>
        {% block footer %}
        <!-- /.admin-content -->
        <div class="admin-footer">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-6">

              </div>
              <!-- /.col-* -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        {% endblock %}
      </div>
      <!-- /.admin-main -->
    </div>
    <!-- /.admin-wrapper -->

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/chartist.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.trackpad-scroll-emulator.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.inlinesvg.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.affix.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.scrollTo.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/nouislider.min.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/jquery.raty.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/wNumb.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/explorer.js' %}"></script> -->
    <!-- <script type="text/javascript" src="{% static 'js/sweetalert2.min.js' %}"></script> -->

    <script type="text/javascript">
      $(document).ready(function(){
        $(".delete").on('click', function(e) {
        e.preventDefault();
        swal({
          text: "Apakah anda yakin ?",
          cancelButtonColor: '#d33',
          showCancelButton: true,
          type: "info",
          customClass: 'swal-wide',
          confirmButtonColor: 'green',
          confirmButtonText: 'Yes'
          }).then((result) => {
              if (result.value) {
                window.location.href = this.getAttribute('href');
              } else {
                e.preventDefault();
                return false
              }
          })
        })
      })
    </script>
    {% block script %}
    {% endblock %}
  </body>
</html>

nxp/templates/backoffice/index.html
{% extends 'backoffice/base.html' %}
{% load static %}
{% block title%} {{title}} {% endblock %}
{% block content %}

<div class="stats">
  <h2 style="text-align: center; margin-bottom: 32px">Sistem Migrasi Data</h2>
  <h5 style="text-align: center">sistem ini dibuat untuk mentrasfer data dari APP lama ke APP baru</h5>
  <h5 style="text-align: center">dengan upload data dari excell dan diteruskan melalui API</h5>
</div>

{% endblock %}

nxp/templates/backoffice/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{% static 'css/trackpad-scroll-emulator.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chartist.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery.raty.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/explorer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/ico/sahabatelvine.ico'%}">
    <title>Login - Explorer</title>
  </head>
  <body class="">
    <div class="page-wrapper">
      <div class="main-wrapper">
        <div class="main">
            <div class="container">
              <div class="row m-top-center">
                <div class="col-sm-4 offset-sm-4">
                  <h3 class="page-title-small">Login</h1>
                  
                  <form method="post" action="{% url 'backoffice:login'%}">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="login-form-email">Username</label>
                      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username">                    </div>
                      {{ auth_form.username.errors }}
                      <!-- /.form-group -->
                    <div class="form-group">
                      <label for="login-form-password">{{ auth_form.password.label }}</label>
                      <input type="password" class="form-control" name="password" required="" id="id_password">                    </div>
                      {{ auth_form.password.errors }}
                      <!-- /.form-group -->
                    <button type="submit" class="btn btn-primary pull-right">Login</button>
                  </form>
                </div>
                <!-- /.col-sm-4 -->
              </div>
              <!-- /.row -->
            <!-- /.container-fluid -->
          </div>
        <!-- /.main -->
      </div>
      <!-- /.main-wrapper -->
    <!-- /.side-wrapper -->
      <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/particles.min.js' %}"></script>
      <script>
          var el = $('#particle-js');
          if (el.length) {
              particlesJS.load('particle-js', '{% static "json/particles.json" %}', function() {});
          }
      </script>
    </body>
</html>